apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"demo-v2","namespace":"canary"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":5678}],"selector":{"app":"demo","version":"v2"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-16T23:25:59Z"
  name: demo-v2
  namespace: canary
  resourceVersion: "1721"
  uid: 7e22aba7-f83f-4ec2-a331-b26f84f722dd
spec:
  clusterIP: 10.107.244.194
  clusterIPs:
  - 10.107.244.194
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5678
  selector:
    app: demo
    version: v2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
