name: SAST (Horusec)
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  horusec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Horusec
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD:/src" \
            horuszup/horusec-cli:v2.9.0-beta.3 \
              horusec start \
                -p /src \
                -P "$(pwd)" \
                --config-file-path=/src/horusec-config.json \
                --return-error \
                --ignore-severity="INFO,LOW,MEDIUM,UNKNOWN" \
                -o=json -O=/src/horusec-report.json

      # <-- ensure this ALWAYS runs, even if the step above fails
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: horusec-report
          path: horusec-report.json
          if-no-files-found: warn
